title: "Meghna Verma"
email: "meghnaverma.phd@gmail.com"
description: "Quantitative Systems Pharmacology | Pharmacometrics | Infectious Disease Modeling"
url: "https://meghna-verma.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"

author:
  name   : "Meghna Verma"
  avatar : "/images/avatar.jpg"
  bio    : "QSP modeler | Pharmacometrics researcher | Blogger"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/meghna-verma"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/YOUR-LINKEDIN"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7776-0433"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/
